import Logo from "./_components/Logo";
import Navigation from "./_components/Navigation";
import { Josefin_Sans } from "next/font/google";
import Header from "./_components/Header";
export const metadata = {
  title: "The Wild Oasis",
  description: "Generated by Next.js",
  icons: {
    icon: "/icon.png",
    apple: "/apple-touch-icon.png",
    shortcut: "/favicon.ico",
  },
};

const JosefinSans = Josefin_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // choose weights you need
  display: "swap",
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${JosefinSans.className} bg-black px-8 py-12 min-h-screen text-primary-100 flex flex-col  `}
      >
        <Header />
        <div className="flex-1   ">
          <main className="max-w-7xl  mx-auto">{children}</main>
        </div>
      </body>
      \
    </html>
  );
}
